name: Deploy site to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm  # 改为 npm
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: 安装依赖
        run: npm ci  # CI 环境推荐使用 npm ci
      
      - name: 构建
        run: npm run build
      
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc_build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4